### ISSUE TITLE
Gradle error when importing the sample project

### ISSUE THREAD

**Issue by chihau** [facebook/network-connection-class#1]
I have this error in gradle when I am importing the sample project to Android Studio.

Error:(16, 0) SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

**Comment by SeyelentEco** [comment]
It's probably just a small configuration issue in Android studio / Gradle.  Here's a relevant StackOverflow article: http://stackoverflow.com/questions/23983221/importing-gradle-project-android-error
