### ISSUE TITLE
[Question] Usage of TrafficStats?

### ISSUE THREAD

**Issue by huyduongtu** [facebook/network-connection-class#10]
I see Android provide this class [TrafficStats ](http://developer.android.com/reference/android/net/TrafficStats.html) from API 8. Why don't you use it instead of reading the file "/proc/net/xt_qtaguid/stats" yourself?
Are there any differences between them?

**Comment by SeyelentEco** [comment]
Good point.  This library was written awhile ago when we had a different set of requirements but now I think it might be better to just use TrafficStats.  I'll submit a diff adding that support in the near future.
