### ISSUE TITLE
[Question] addBandwidth() calculations done in bits/ms but getDownloadKBitsPerSecond()?

### ISSUE THREAD

**Issue by entrpn** [facebook/network-connection-class#14]
When calling addBandwidth(), the calculations are done in bits/ms, but the getter is named getDownloadKBitsPerSecond(). Meaning it returns kpbs. Is that right? It seems to me that this bandwidth average is actually bits/ms? Thanks.

**Comment by entrpn** [comment]
Never mind. After looking more at the code, this method name is correct.

In case someone else is confused by this, why it works:

mValue (bits/ms) \* (1000 ms / 1 second) \* (1Kb/1000 bits)  = mValue (Kb/s)

**Comment by YodaEmbedding** [comment]
Well, that's confusing since:

```
KB == 1024
kB == 1000
```

...Perhaps that should have been documented?
