### ISSUE TITLE
com.android.dex.DexException: Multiple dex files define Ljavax/annotation/CheckForNull;

### ISSUE THREAD

**Issue by Guro** [facebook/network-connection-class#4]
After adding 
compile 'com.facebook.network.connectionclass:connectionclass:1.0.0'
to gradle config we are getting this error:
com.android.dex.DexException: Multiple dex files define Ljavax/annotation/CheckForNull;

can you suggest anything?

**Comment by SeyelentEco** [comment]
We haven't seen this from anyone else.  Can you check to make sure you aren't including a jar and using the gradle?

**Comment by Guro** [comment]
Yes I'm sure.
Ok thats maybe because of our project configuration, ill investigate it more and try it on clean project.

Closing issue for now, will reopen it if will have more detailed info.
