### ISSUE TITLE
Cutomization of bandwidth

### ISSUE THREAD

**Issue by vivekgidmare** [facebook/network-connection-class#8]
Can we have way to customize bandwidth range instead of fixed? So developer can customize it like for poor under 50Kbps depends on their need.

**Comment by rrong** [comment]
The values for the bandwidth ranges are in ConnectionClassManager.java:
https://github.com/facebook/network-connection-class/blob/master/connectionclass/src/main/java/com/facebook/network/connectionclass/ConnectionClassManager.java#L37

You can change `DEFAULT_POOR_BANDWIDTH` to 50 for your example to customise the bandwidth ranges.

**Comment by SeyelentEco** [comment]
I agree with @rrong, these values were hardcoded because they were based on a lot of data and analysis.  You can change them locally for your setting if you want but we want a consistent value for most people so we can easily compare data.
