### ISSUE TITLE
[Question] What is the approriate value of network connection timeout

### ISSUE THREAD

**Issue by huyduongtu** [facebook/network-connection-class#9]
I'm applying your library into my application. My application mostly fetches images from server.
I wanna to know what is the network connection timeout value for each network quality?
How many network threads do you set?
Sorry that it seems not be related to this library. Thanks.

**Comment by Alayode** [comment]
which library are you referring to ?

**Comment by huyduongtu** [comment]
I'm using HttpClient for android 2.2 and OkHttpClient for android version >= 2.3.
I wanna to know what is the appropriate value for network timeout for each network quality.
Could you give me some advise? Thanks.

**Comment by SeyelentEco** [comment]
We don't recommend changing the timeout by network quality.  A consistent network timeout allows your application to act consistently and be more predictable.
